### ISSUE TITLE
Admin edit functions

### ISSUE THREAD

**Issue by rshorey** [opencivicdata/python-opencivicdata-django#34]
- [x] bills
- [x] divisions
- [x] jurisdictions
- [x] organizations
- [x] people
- [x] posts
- [x] votes

**Comment by rshorey** [comment]
What happens to garbage data in the database? I don't love the idea of being able to delete from the interface, but should we be able to if we accidentally scrape a legislator named "vacant" or something like that?

**Comment by rshorey** [comment]
I'm making memberships only edit-able through people (and maybe also orgs?) because on their own they're extremely confusing.

**Comment by rshorey** [comment]
Two remaining problems with people/organizations:
1) new inlines cannot be added due to issues with django-uuidfield. @jamesturk is looking into migrating to django's internal uuid functionality.
2) membership IDs are exposed to editing in membership inlines inside person. @jamesturk is also looking into that fix.

Otherwise I think I've taken care of fixes for people/orgs.

**Comment by jamesturk** [comment]
Django 1.8 migration is in #31 looking at UUIDfield now

**Comment by jamesturk** [comment]
Rachel- would it be tough to test if the branch I just pushed (see above commit) fixes the inline uuid issue, it is a simpler fix than dropping django-uuidfield altogether, though we may still want to do that

**Comment by rshorey** [comment]
yep, will do!

**Comment by rshorey** [comment]
@jamesturk I'm still getting uuid problems. I'm also getting some other new problems involving select_related which I will investigate.

**Comment by jamesturk** [comment]
OK, no worries, I think we may need to do the uuid flip after all

On Tue, May 19, 2015 at 12:47 PM, Rachel <notifications@github.com> wrote:

> @jamesturk <https://github.com/jamesturk> I'm still getting uuid
> problems. I'm also getting some other new problems involving select_related
> which I will investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/python-opencivicdata-django/issues/34#issuecomment-103587472>
> .
>



-- 

James Turk
Labs Director | Sunlight Foundation <http://www.sunlightfoundation.com/>
202-558-8723 | @JamesTurk <https://twitter.com/jamesturk>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by rshorey** [comment]
I'll wait on other fixes until that's done then.
